- hosts: webserver
  vars_files:
  - "{{ansible_facts['os_family']}}.yml"
  tasks:
  - name: "installing software"
    package:
     name: "{{ software }}"
     state: present

  - name: "making index file for webserver"
    template:
     src: "index.html"
     dest: "/var/www/html/index.html"

  - name: "starting the service"
    service:
     name: "{{ service_name }}"
     state: started
